pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot-preview[bot]
      - status-success=build (3.6, macos-latest)
      - status-success=build (3.7, macos-latest)
      - status-success=build (3.8, macos-latest)
      - status-success=build (3.6, windows-latest)
      - status-success=build (3.7, windows-latest)
      - status-success=build (3.8, windows-latest)
      - status-success=build (3.6, ubuntu-latest)
      - status-success=build (3.7, ubuntu-latest)
      - status-success=build (3.8, ubuntu-latest)
    actions:
      merge:
        method: squash
