language: python
python:
  - '2.7'
  - '3.4'
services:
  - postgresql
before_script:
  - psql -c 'create database browser_calls;' -U postgres
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run manage.py test --settings=twilio_sample_project.settings.test
env:
  - TWILIO_ACCOUNT_SID=ACXXXXXXXXXXXXXXXXX TWILIO_AUTH_TOKEN=YYYYYYYYYYYYYYYYYY TWILIO_NUMBER=+15555555555 TWIML_APPLICATION_SID=APZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
after_success:
  - coveralls
